### ISSUE TITLE
Point of contact for each lesson

### ISSUE THREAD

**Issue by chendaniely** [carpentries/maintainer-RFCs#11]
The vast majority of our maintainers only maintain a single lesson (there are counts across swc, dc, and lc).
There are 161 maintainers across 54 lessons.

   | Repos per Maintainer  | Number of Maintainers |
   | --------------------: | ---------------------: |
   | 1                     | 129                    |
   | 2                     |  25                    |
   | 3                     |   6                    |
   | 4                     |   1                    |

   ```
          0        20        40        60        80        100       120
   M    +-+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
   a    |                                                                       |
   i  1 + =================================================================     +
   n    |                                                                       |
   t  2 + ============-                                                         +
   a    |                                                                       |
   i  3 + ===                                                                   +
   n    |                                                                       |
   e  4 + -                                                                     +
   r    |                                                                       |
   s    +-+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
          0        20        40        60        80        100       120
   
                                       Repositories
   ```
   *rotated by Trevor Keller to utilize better x- than y-resolution*
   *code for plots can be found here: https://github.com/chendaniely/maintainers

Library Carpentry flags a "lead maintainer" in their [lessons](https://librarycarpentry.org/lessons/),
and this seems like a great idea to implement Carpentries-wide if we need a way to get a broad set of feedback from maintainers.
We do not want it to seem and do not want it to be a role where there is going to be a lot more work involved.

Examples of things the "lead maintainer" would be responsible for:

- Comments on RFCs
- Adding feedback to the upcomming lesson templates

I would also add that we can make the comments and feedback something as simple as "use this emoji to vote for/against",
and maybe use different langauge to iterate that we are not dumping more work for the "lead" (an example phrase could be "point person").

**Comment by sstevens2** [comment]
Seems like a good idea.  Might be good for this person to also coordinate with the other maintainers on the lesson.  For example, assigning issues/PRs to other maintainers in the group or helping to facilitate a meeting about goals.  For the docker incubator lesson, I've planned a meeting with all the maintainers to discuss the goals for the lesson in the next year.  Might be a good action for the Lead Maintainer.  I know we don't want to make it a lot more work but I'm feeling like that might not be asking too much (as long as you aren't lead maintainer on many lessons).

**Comment by annajiat** [comment]
Pros:
- the idea of having a point of contact / lead maintainer is good as it is more scalable and sustainable. 
- it might be helpful for meetings or beta programs.

Cons:
We might wish to ping all maintainers for comments and feedback:
- We do not know how many responses we are going to receive. Lead maintainer might have missed to provide feedback whereas other maintainers might have provided feedback if they were reached out.
- Having more data might lead to us being able to make more informed decisions.
