### ISSUE TITLE
Maintainer Alumni Status

### ISSUE THREAD

**Issue by chendaniely** [carpentries/maintainer-RFCs#12]
## What can alumni do?

One of the core components of a community of practice is managing the influx and efflux of people.
We want to be able to borrow the alumni badging system used by other parts of The Carpentries,
so we can give credit to our maintainers and also give alumni a way to still contribute to the carpentries
and have a path to being a maintainer again.

You can contact The Carpentries team or the Community Maintainer Lead if a current maintainer needs to step out,
but what would alumni still be able to do and not be able to do?

Since one hurdle in the current lesson maintenance workflow is getting someone to "approve" and "review" a pull-request,
giving the alumni the ability to approve of PRs seems like a good way to keep reviewing resources high.

The current proposal is:

- Alumni are *not* able to:
  - Write access to the lesson
- Alumni may:
  - "approve"/review a PR
  - attend/participate in all maintainer communication channels

Is there anything else that may be missing from this list?

## How do alumni re-activate?

The Trainers have a "re-activation" plan:

- < 3 months no requirements - contact team@carpentries.org to request reinstatement
- 3-12 months: meet with the Director of XXXXX to catch up on the latest news & discuss plans for re-activating
- 12 months: Review maintainer guidelines, attend a maintainer meeting, catch up, discuss

Instructors and trainers are mostly in a pool of instructors who can teach a workshop,
whereas maintainers are "assigned" to a particular lesson, 
so the process of maintainer alumni re-activating will be different since there might not be "space" in a lesson.

One potential idea for alumni re-activation would be to re-commit to the maintainer goals (separate RFC),
and

1. work with the lesson leads to see if they can be added to their maintainer list
2. Be in a "free agency" role where other lessons who need help can "recruit" from before a new batch of maintainers can be onboarded.

**Comment by annajiat** [comment]
I would like to vote for a longer duration than 3 months, may be 6 months?

How about including some engagement with the templates and RFCs as a part of the re-activation plan?
