### ISSUE TITLE
Maintainer active status renewal

### ISSUE THREAD

**Issue by chendaniely** [carpentries/maintainer-RFCs#13]
Not every discussion topic needs to hear from all 161 maintainers (#11),
but some system should be in place to see if each maintainer still wants to remain in "active" status
or moved to "alumni" status (#12).

The maintainer onboarding process should have a place where each potential maintainer lists their plans for the year.
We can incorporate this yearly plan/goal for all of our maintainers once a year to make sure they still want to be active,
and at the very least still responding to communication attempts.

The call for maintainer renewals can be done in Q1 of the year so we can plan to onboard new maintainers in Q2-Q3.

**Comment by jsta** [comment]
I really like this idea! Who would be responsible for finding out if maintainers are responding to communication attempts?

**Comment by chendaniely** [comment]
This is still something I'm thinking about and everything is up for discussion/change:

@jsta probably me ;D (and a job for the community maintainer leads after me).
For the rest of the year, I want to say that might be the "maintainer lead" #11 since there will only be 1 mandatory ping from the Carpentries level every year.

**Comment by sstevens2** [comment]
I agree it would be good to have a process to check in with maintainers and see if they still plan to be active each year.

**Comment by annajiat** [comment]
In addition to a ping via email, I would like to propose an automated DM in slack as well, if possible. Emailing is very important but sometimes email might find its way to spam.
