### ISSUE TITLE
Remote themes [WIP]

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/maintainer-RFCs#2]
## Timeline

If you have any questions or concerns about this change, please post in this thread by **[DAY TIME](link)**. @fmichonneau, myself, and members of the @carpentries/lesson-infrastructure-committee  will respond here to answer questions and address concerns. If you would like to comment on the technical implementation, you may also [leave feedback on the PR in the styles repo](link to be added) which implements this change.

**Comment by ErinBecker** [comment]
## Context



## Current Status

## How will these changes affect me?



## Timeline

If you have any questions or concerns about this change, please post in this thread by **[DAY TIME](link)**. @fmichonneau, myself, and members of the @carpentries/lesson-infrastructure-committee  will respond here to answer questions and address concerns. If you would like to comment on the technical implementation, you may also [leave feedback on the PR in the styles repo](link to be added) which implements this change.

**Comment by tobyhodges** [comment]
@ErinBecker @zkamvar can this be closed, following the transition of official lessons to the new infrastructure?
